### ISSUE TITLE
Dashboard Layout

### ISSUE THREAD

**Issue by flywire** [rin67630/SCC2Buck#12]
Layout
- Generally pretty good, most important information is V Bat then V Pan in centre top third of screen

Terms
- PV might be a more accepted abbreviation than Pan
- Aux is good, other documentation (including schematics) needs to be consistent

Colour
- pastels are nice on the eyes, yellow would be more naturally associated with PV

Setpoint
- use V rather than mV (regardless of source code) to be consistent with general usage and allow user to focus on number before or fraction after decimal

Gauges
- This is a hard way to interpret data compared to common digital V/A/W meters which often use three colours (eg red/green/blue) to display values
- percentage rather than value can be useful but probably not both at same time

Chart
- simple line charts are a good way of communicating information but things like 3d shading, which appears to be shown on the points, make data harder to interpret

Documentation
- Why is the data shown?  That explains how it is used.

**Comment by rin67630** [comment]
Everybody can tailor it's own layout. I provided an example only. 
Thinger.io is absolutely open with respect to that.
The only gotcha is that currently the setpoint is in mV in the ESP. I would have needed a conversion.
