### ISSUE TITLE
issue in Soft-Power-MPPT/Software/e_Data.ino

### ISSUE THREAD

**Issue by trif55** [rin67630/SCC2Buck#13]
http.begin(WifiClient, OPEN_WEATHER_MAP_URL);

this line 173 i believe, gives an error, that error persists when changing WifiClient to WiFiClient and to WiFi

**Comment by rin67630** [comment]
By the way this project is retired. It did not work reliably enough.

The software is now obsolete. The http library has also changed and require now instanciation.

**Comment by trif55** [comment]
Hi Rin, I know you retired this project due to the buck modules failing but I'm still willing to work on it and see how it goes for my use case, 

if you'd be willing to add me as a collaborator I'd like the chance to do my best and learn to maintain it,

Thank you

**Comment by amgednoomen** [comment]
Good
