### ISSUE TITLE
Thinger_SoftPowerControl.json is missing?

### ISSUE THREAD

**Issue by trif55** [rin67630/SCC2Buck#14]
It's mentioned in the help but no longer exists? has it all been combined into Thinger_SoftPowerStatistics.json? I don't see the dashboard graphs I can see in the pictures

**Comment by rin67630** [comment]
In fact the dashboards are built online at Thinger.io  by the user. 
The .json files were for my own convenience, they are user specific.

By the way this project is retired. It did not work reliably enough.
