### ISSUE TITLE
I just want to tell, there is someone doing the same with STM32

### ISSUE THREAD

**Issue by TeguhTeknisi** [rin67630/SCC2Buck#3]
Here the link https://github.com/szbeni/solar

Hardware main parts:
STM32 MCU (bluepill STM32F103)
SZBK07 DCDC module (LM25116 DCDC driver chip and other electroics removed just power electronic parts used)
250W solar panel 36V nominal voltage
Split charge relay for charging from engine, when driving (separate from this circuit)
55Ah and 110Ah 12V leisure batteries in parallel
3x ACS712 current sensors
ADS1115 ADC for current measurement
FAN for cooling power electronics
Bluetooth UART module for communnication

**Comment by rin67630** [comment]
Thank you for the info. 
He is using the PWM injection from https://github.com/farmerkeith/SolarChargerSZBK07ModuleV2 
I found out, that a DC injection smoothed by a RC filter increases the efficiency of the buck converter.
The SZBK07 alone has a 40mA quiescent (no-load) current, to high for low power panels in cloudy regions.

**Comment by TeguhTeknisi** [comment]
Your welcome.

Btw, i want to build Soft-Power-MPPT, because i have wemos d1, NodeMCU laying around,
But after read in here:
1. https://diysolarforum.com/threads/low-power-bad-weather-solar-harvesting-an-attempt-to-build-a-better-scc.13847/
2. https://diysolarforum.com/threads/an-attempt-to-build-a-better-scc-next-step.15023/
3. https://diysolarforum.com/threads/softpower-universal-version-for-panels-21w-and-panels-300w.16989

lookslike, i need to wait until its complete.
i hope you can make a youtube video for showing Soft Power MPPT in action with 100WP or 200WP.

Btw, I want to make Solar System with 100WP or 2 x 100WP plus 3S 18650 40A  i don't have the PV yet, still saving money.
Right now, i'am colecting Lithium 18650 battery, i took it from Pisen LCD Power Station 20.000mAH with 8 Battery inside. 
i have 4 Pisen Power Bank 20.000mAh right now, still need more to buy.
( i found a video tutorial to take out the battery in here https://www.youtube.com/watch?v=YM6E39Lmwfo )

Thanks alot.

**Comment by szbeni** [comment]
Hi!
I have tried using the PWM injection method to control the DC DC module, but it didn't give enough control for me over the power stage, so I added a gate driver chip and controlling the FETs with that instead of the LM25116 chip.
Beni

**Comment by rin67630** [comment]
The DC injection gives -100%...+20% 
That is perfect to control battery chargers.

Let us please continue on Discord:
Open Solar Project / Development [https://discord.com/channels/720686061159841852/792440881831608340](url)

**Comment by TeguhTeknisi** [comment]
i never used discord for a long time ( since G Plus it shutdown ), i use it for chat with a farmer fellow in G Plus comunity.
so i reset the password, go to the link above, and "You find yourself in a strange place. .... "
then close and i will forget the discord.

i hope you can update the post in https://diysolarforum.com/threads/softpower-universal-version-for-panels-21w-and-panels-300w.16989/
i will follow in the forum and this github, so i can try to build it when you post the update in there.

Thanks a lot.
