### ISSUE TITLE
Simplify Presentation

### ISSUE THREAD

**Issue by flywire** [rin67630/SCC2Buck#5]
Conceptually this is a very simple project but the presentation of many options is very complicated and confusing. This is unnecessary because most changes are component specifications requiring small circuit changes. It is suggested to explain common things simply before explaining the detail of the differences. Part of the problem is probably from designing the project in EasyEDA which does not support overlays like packages such as KiCad.

![Soft Power Overlays B](https://user-images.githubusercontent.com/11288701/105553228-1d4d2680-5d59-11eb-89e4-196f2d319179.png)
**Figure:** Overlay of all options demonstrating main changes are buck converter specifications and power sensors

The project converts solar panel power to battery power. Clearly identifying and describing the parts before the custom changes for different components would make it easier to understand. It would allow easy direct reference to components such as the Management Buck which powers the microcontroller. The Converter could be more simply described as usually a small buck and optionally a larger buck.

The schematic wiring would be clearer and more generic if the oled was placed next to the power sensors on the I2C bus. The detail is also inconsistent, for example, the blocking diode is shown but not temperature management and fusing.

**Comment by flywire** [comment]
The text seems reasonable so the issue is how schematics communicate it:
1. schematics are ordered differently to text
1. changes are not obvious, maybe highlight changes from preferred option
1. difficult to compare one sheet with another
1. Add notes to schematics, eg: INA3221 module maximum of 26V, do not exceed "12V class" of panels (Voc=~20V, Vpp=~18V) or "12V" batteries.

**Comment by rin67630** [comment]
OK, I will not change to Kicad in the middle of the development. 
You are right I were just to creative... Let us just finish one version.
I will now just concentrate on the INA3221 version in the 12V class and issue an addendum for all possible variants.
The priority now is to document the hardware and finalize the software.

**Comment by rin67630** [comment]
You are welcome to help me reforming the schematic analysis to shift all optional stuff as differences at the end.
I must now solder...

**Comment by flywire** [comment]
That's a good plan and good choice. I'll canvas some forums for good ideas to present designs with minor changes.

**Comment by rin67630** [comment]
I have now profoundly revamped the schematics.
I just keep 3 variants:
The INA3221 full blown
The minimal version INA226 as device power supply
A Passive Logger.
The hardware tinkering is explained and the chip identifiers are consistent in pictures diagrams and layout.
I just must add a functional description.
Just take a look at the current state and give me feed-back.

**Comment by flywire** [comment]
Portrait Block Diagram [code](http://interactive.blockdiag.com/?compression=deflate&src=eJx9kU9PwzAMxe_9FFYPnEAV52pIaze4gJjYcZqQt3htRJSUNIWVad8dp39QtLHdHP2en1_sQwRgrCTt0EmjYQKVsc6idAwE7bBR7r0usSJG1jRakNiYfRoxnsJK4YYUk3hpFFpYoCYVr1OGWQAX5pss5EZ_kXVke0EeCBg5a4bOWQCmQhgd30LtWuUTCKxLEp1sHsqavVQcoD2T-jduP4aex6AnQ8dZ2n7m039mMEqumXZ7uHuArP80VzwEyrGhIE0Wlfzp1jsEZxEPPPW83MNNBe--OnABsDXKWB9UyaJ0haU2TjvQTc-Den46ZN3D_C8wQJIAadywSNPegZKaQO5AoRb1ls8-ivoeWF372eA8u646RhH7wTMxE105vQ_W_0afjbQk_GE8zEL4grqFG3itvBuq8TKT87skyWjtc4ceS9I1Be7MfYDLkY-_pTDxNg)

![image](https://user-images.githubusercontent.com/11288701/106217405-470abf80-6229-11eb-8aef-741ad035c548.png)

Landscape Block Diagram [code](http://interactive.blockdiag.com/?compression=deflate&src=eJx9kU9PwzAMxe_9FFYPnEAV52pIaze4gJjYcZqQt3htRJSUNIWVad8dp39QtLHdHP3es1_sQwSQJGCsJO3QSaNhApWxzqJ0zATtsFHuvS6xIkbWNFqQ2Jh9GjGewkrhhhSTeGkUWligJhWvU4ZZABfmmyzkRn-RdWR7QR4IGDlrBucsAFMhjI5voXat8gkE1iWJTjYPZc1eKg7Qnkn9G7cfg-cx8GToOEvbz3z6rxmMkmtNuz3cPUDWf5orHgLlaChIk0Ulf7r1DsFZxANPe172sKng3VcHLgC2RhnrgypZlK6w1MZpB7rpeVDPT4ese5j_Be7uTxo3LNK0d6CkJpA7UKhFveWzBwZYXfvWoJpdVx2jiCfCMzETXTm9D3b_Rp-NtCT8VTzMQviCuoUbeK18N1TjWSbnR0mSsbXPHfZYkq4p6M7cB7gc-fgLwerxNg)

![image](https://user-images.githubusercontent.com/11288701/106217496-791c2180-6229-11eb-9fd1-00013998f9cf.png)

Enable legend in code if required.
